"""add base_kline

Revision ID: 398dd8858bae
Revises: 
Create Date: 2022-05-21 20:59:08.365186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '398dd8858bae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('exchange_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('exchange_id')
    )
    op.create_table('symbols',
    sa.Column('symbol_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('base_currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quote_currency', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('symbol_id')
    )
    op.create_table('timeframes',
    sa.Column('timeframes_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timeframes', sa.VARCHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('timeframes_id')
    )
    op.create_table('base_klines',
    sa.Column('kline_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.BigInteger(), nullable=False),
    sa.Column('timeframes_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', mysql.TIME(fsp=3), nullable=False),
    sa.Column('end_time', mysql.TIME(fsp=3), nullable=False),
    sa.Column('open', sa.NUMERIC(precision=28, scale=13), nullable=False),
    sa.Column('high', sa.NUMERIC(precision=28, scale=13), nullable=False),
    sa.Column('low', sa.NUMERIC(precision=28, scale=13), nullable=False),
    sa.Column('close', sa.NUMERIC(precision=28, scale=13), nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=28, scale=13), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=28, scale=13), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.exchange_id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.symbol_id'], ),
    sa.ForeignKeyConstraint(['timeframes_id'], ['timeframes.timeframes_id'], ),
    sa.PrimaryKeyConstraint('kline_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_klines')
    op.drop_table('timeframes')
    op.drop_table('symbols')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
